[tool:pytest]
DJANGO_SETTINGS_MODULE = floodguard.test_settings
addopts = --reuse-db --tb=short
cache_dir = /tmp/floodguard-pytest-cache
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
