# Generated by Django 4.2.30 on 2026-05-06 21:18

from django.db import migrations
from django.contrib.auth.models import Group


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: Group.objects.get_or_create(name='EmergencyTeam'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
