# Generated by Django 4.2.30 on 2026-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_emergency_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertzone',
            name='manual_override_active',
            field=models.BooleanField(default=False, help_text='When active, suppresses automatic alert triggering for this zone'),
        ),
        migrations.AddField(
            model_name='alertzone',
            name='manual_override_until',
            field=models.DateTimeField(blank=True, help_text='Override is active until this time (if set)', null=True),
        ),
    ]
