# Generated by Django 4.2.30 on 2026-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alertzone_manual_override_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the message was delivered', null=True),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='pending', help_text='Delivery status of the alert', max_length=20),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='provider_message_id',
            field=models.CharField(blank=True, help_text="Message ID from the SMS provider (e.g., Africa's Talking)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='cluster_id',
            field=models.CharField(blank=True, help_text='Identifier for geographic cluster of related reports', max_length=50, null=True),
        ),
    ]
