# Generated by Django 4.2.30 on 2026-05-07 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alertlog_delivered_at_alertlog_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the incident was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='Authority user who acknowledged this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('acknowledged', 'Acknowledged')], default='pending', max_length=12),
        ),
    ]
