# Generated by Django 4.2.30 on 2026-05-07 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_incidentreport_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodreading',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Calculated risk score (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
