# Generated by Django 4.2.30 on 2026-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alertzone_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether the phone number has been verified via OTP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_enabled',
            field=models.BooleanField(default=True, help_text='User consent to receive SMS alerts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS alerts (international format: +[country code][number])', max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['-triggered_at'], name='core_alertl_trigger_db1b79_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['delivery_status'], name='core_alertl_deliver_1bc399_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['alert_zone', '-triggered_at'], name='core_alertl_alert_z_eb495e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertzone',
            index=models.Index(fields=['risk_score'], name='core_alertz_risk_sc_6cee94_idx'),
        ),
        migrations.AddIndex(
            model_name='alertzone',
            index=models.Index(fields=['manual_override_active'], name='core_alertz_manual__3e4ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertzone',
            index=models.Index(fields=['-updated_at'], name='core_alertz_updated_acf7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='floodreading',
            index=models.Index(fields=['timestamp'], name='core_floodr_timesta_88a62d_idx'),
        ),
        migrations.AddIndex(
            model_name='floodreading',
            index=models.Index(fields=['-timestamp'], name='core_floodr_timesta_b59b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='floodreading',
            index=models.Index(fields=['risk_score'], name='core_floodr_risk_sc_ffd8de_idx'),
        ),
        migrations.AddIndex(
            model_name='floodreading',
            index=models.Index(fields=['location'], name='core_floodr_locatio_4752e2_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['-created_at'], name='core_incide_created_16e2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status'], name='core_incide_status_764eda_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity'], name='core_incide_severit_743d98_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['cluster_id'], name='core_incide_cluster_aef1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['location'], name='core_incide_locatio_90dba0_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['submitted_by', '-created_at'], name='core_incide_submitt_7fc29e_idx'),
        ),
    ]
