# Generated by Django 4.2.30 on 2026-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_phone_verified_userprofile_sms_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodreading',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Full multi-source feature vector from data ingestion'),
        ),
    ]
