# Generated by Django 4.2.30 on 2026-07-12

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_floodreading_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(help_text='Date for which this prediction is made')),
                ('risk_score', models.FloatField(help_text='Predicted risk score (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('water_level_metres', models.FloatField(blank=True, help_text='Predicted water level in metres', null=True)),
                ('river_discharge_m3s', models.FloatField(blank=True, help_text='Predicted river discharge in m3/s', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Prediction confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source data used for prediction')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.alertzone')),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [
                    models.Index(fields=['zone', 'target_date'], name='core_floodp_zone_id_62f32d_idx'),
                    models.Index(fields=['-predicted_at'], name='core_floodp_predict_33481e_idx'),
                ],
                'unique_together': {('zone', 'target_date')},
            },
        ),
    ]
