# Generated by Django 4.2.30 on 2026-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_zone_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('community', 'Community Group'), ('school', 'School'), ('ngo', 'NGO'), ('government', 'Government'), ('business', 'Business')], max_length=20)),
                ('member_count', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('enrolled_date', models.DateField()),
                ('trained', models.BooleanField(default=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-enrolled_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achieved_date', models.DateField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('community', 'Community'), ('business', 'Business'), ('partnership', 'Partnership')], max_length=20)),
                ('evidence_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-achieved_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('alerts_sent', models.IntegerField(default=0)),
                ('reports_received', models.IntegerField(default=0)),
                ('reports_verified', models.IntegerField(default=0)),
                ('high_risk_events', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('zones_monitored', models.IntegerField(default=0)),
                ('uptime_pct', models.FloatField(default=100.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.RenameIndex(
            model_name='alertzoneactivity',
            new_name='core_alertz_zone_id_a0c753_idx',
            old_name='zone_created_idx',
        ),
        migrations.RenameIndex(
            model_name='alertzoneactivity',
            new_name='core_alertz_user_id_903382_idx',
            old_name='user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='alertzoneactivity',
            new_name='core_alertz_source_1ee928_idx',
            old_name='activity_source_idx',
        ),
        migrations.RenameIndex(
            model_name='alertzoneactivity',
            new_name='core_alertz_created_21ec4d_idx',
            old_name='activity_created_idx',
        ),
        migrations.AlterField(
            model_name='alertzoneactivity',
            name='source',
            field=models.CharField(choices=[('static', 'Static / Predefined'), ('dynamic', 'Dynamic / GPS-derived'), ('user', 'User-created'), ('imported', 'Imported')], default='dynamic', max_length=20),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['-period_start'], name='core_monthl_period__30bd42_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['-generated_at'], name='core_monthl_generat_17c39b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['category'], name='core_milest_categor_e67478_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['is_public'], name='core_milest_is_publ_2a18db_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['-achieved_date'], name='core_milest_achieve_71f982_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarygroup',
            index=models.Index(fields=['group_type'], name='core_benefi_group_t_4a2447_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarygroup',
            index=models.Index(fields=['trained'], name='core_benefi_trained_310a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarygroup',
            index=models.Index(fields=['-enrolled_date'], name='core_benefi_enrolle_e76d30_idx'),
        ),
    ]
