# Generated by Django 4.2.30 on 2026-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_beneficiarygroup_milestone_monthlyreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('govt_national', 'Government Official (National)'), ('govt_county', 'Government Official (County)'), ('emergency_responder', 'Emergency Responder'), ('meteo_officer', 'Meteorological Officer'), ('ngo_humanitarian', 'NGO/Humanitarian Worker'), ('citizen', 'Citizen/Public User'), ('researcher', 'Researcher/Analyst')], default='citizen', help_text='User role in the system', max_length=30),
        ),
    ]
