# Generated by Django 4.2.30 on 2026-07-28 14:00

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_extend_user_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boundary_type', models.CharField(choices=[('country', 'Country'), ('county', 'County'), ('constituency', 'Constituency'), ('ward', 'Ward'), ('village', 'Village'), ('river', 'River'), ('protected_area', 'Protected Area')], max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='natural_earth', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('new', 'New'), ('monitoring', 'Monitoring'), ('active', 'Active'), ('escalated', 'Escalated'), ('stabilizing', 'Stabilizing'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='new', max_length=20)),
                ('creation_source', models.CharField(choices=[('weather', 'Weather Update'), ('community', 'Community Report'), ('river_discharge', 'River Discharge'), ('rainfall', 'Extreme Rainfall'), ('satellite', 'Satellite/Open Data'), ('authority', 'Authority Input'), ('merged', 'Merged from multiple zones'), ('split', 'Split from parent zone')], max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('risk_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cause', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('population_exposed', models.IntegerField(blank=True, null=True)),
                ('buildings_affected', models.IntegerField(blank=True, null=True)),
                ('roads_affected', models.JSONField(blank=True, default=list)),
                ('critical_infrastructure', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('resource_requirements', models.JSONField(blank=True, default=dict)),
                ('evacuation_advice', models.TextField(blank=True)),
                ('emergency_response_level', models.CharField(blank=True, max_length=50)),
                ('authority_override', models.BooleanField(default=False)),
                ('override_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-risk_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_hours', models.IntegerField()),
                ('predicted_risk_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('spread_direction', models.CharField(blank=True, max_length=100)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='H3Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_index', models.CharField(db_index=True, max_length=50, unique=True)),
                ('resolution', models.IntegerField()),
                ('centroid_lat', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('population_density', models.FloatField(blank=True, null=True)),
                ('road_density', models.FloatField(blank=True, null=True)),
                ('building_density', models.FloatField(blank=True, null=True)),
                ('terrain_complexity', models.FloatField(blank=True, null=True)),
                ('historical_flood_frequency', models.FloatField(default=0.0)),
                ('current_risk_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='alertzone',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Confidence in zone accuracy (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='alertzone',
            name='creation_source',
            field=models.CharField(choices=[('weather', 'Weather Update'), ('community', 'Community Report'), ('river_discharge', 'River Discharge'), ('rainfall', 'Extreme Rainfall'), ('satellite', 'Satellite/Open Data'), ('authority', 'Authority Input'), ('merged', 'Merged from multiple zones'), ('split', 'Split from parent zone')], default='authority', help_text='Source of zone creation', max_length=30),
        ),
        migrations.AddField(
            model_name='alertzone',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the zone expires (null for permanent)', null=True),
        ),
        migrations.AddField(
            model_name='alertzone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the zone is currently active'),
        ),
        migrations.AddField(
            model_name='alertzone',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional zone metadata'),
        ),
        migrations.CreateModel(
            name='ZoneLifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('new', 'New'), ('monitoring', 'Monitoring'), ('active', 'Active'), ('escalated', 'Escalated'), ('stabilizing', 'Stabilizing'), ('inactive', 'Inactive'), ('archived', 'Archived')], max_length=20)),
                ('to_state', models.CharField(choices=[('new', 'New'), ('monitoring', 'Monitoring'), ('active', 'Active'), ('escalated', 'Escalated'), ('stabilizing', 'Stabilizing'), ('inactive', 'Inactive'), ('archived', 'Archived')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_logs', to='core.dynamiczone')),
            ],
        ),
        migrations.CreateModel(
            name='H3CellRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('neighbor', 'Neighbor'), ('k_ring', 'K-Ring')], max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.h3cell')),
                ('target_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.h3cell')),
            ],
        ),
        migrations.AddIndex(
            model_name='h3cell',
            index=models.Index(fields=['resolution'], name='core_h3cell_resolut_923e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='h3cell',
            index=models.Index(fields=['-current_risk_score'], name='core_h3cell_current_704b47_idx'),
        ),
        migrations.AddIndex(
            model_name='h3cell',
            index=models.Index(fields=['-last_updated'], name='core_h3cell_last_up_7b62a0_idx'),
        ),
        migrations.AddField(
            model_name='floodpropagation',
            name='predicted_cells',
            field=models.ManyToManyField(related_name='propagation_predictions', to='core.h3cell'),
        ),
        migrations.AddField(
            model_name='floodpropagation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='core.dynamiczone'),
        ),
        migrations.AddField(
            model_name='dynamiczone',
            name='h3_cells',
            field=models.ManyToManyField(related_name='dynamic_zones', to='core.h3cell'),
        ),
        migrations.AddField(
            model_name='dynamiczone',
            name='merged_from',
            field=models.ManyToManyField(blank=True, related_name='merged_into', to='core.dynamiczone'),
        ),
        migrations.AddField(
            model_name='dynamiczone',
            name='parent_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_zones', to='core.dynamiczone'),
        ),
        migrations.AddField(
            model_name='administrativeboundary',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.administrativeboundary'),
        ),
        migrations.AddIndex(
            model_name='zonelifecyclelog',
            index=models.Index(fields=['zone', '-created_at'], name='core_zoneli_zone_id_273461_idx'),
        ),
        migrations.AddIndex(
            model_name='h3cellrelationship',
            index=models.Index(fields=['source_cell', 'relationship_type'], name='core_h3cell_source__3eb265_idx'),
        ),
        migrations.AddIndex(
            model_name='h3cellrelationship',
            index=models.Index(fields=['target_cell', 'relationship_type'], name='core_h3cell_target__36ba78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='h3cellrelationship',
            unique_together={('source_cell', 'target_cell', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='floodpropagation',
            index=models.Index(fields=['zone', 'forecast_hours'], name='core_floodp_zone_id_e7f742_idx'),
        ),
        migrations.AddIndex(
            model_name='floodpropagation',
            index=models.Index(fields=['-created_at'], name='core_floodp_created_ab1f99_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamiczone',
            index=models.Index(fields=['state'], name='core_dynami_state_2dff88_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamiczone',
            index=models.Index(fields=['creation_source'], name='core_dynami_creatio_a3cb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamiczone',
            index=models.Index(fields=['-risk_score'], name='core_dynami_risk_sc_881eab_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamiczone',
            index=models.Index(fields=['-updated_at'], name='core_dynami_updated_e1fab6_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamiczone',
            index=models.Index(fields=['priority'], name='core_dynami_priorit_e0ad0a_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeboundary',
            index=models.Index(fields=['boundary_type'], name='core_admini_boundar_bf450d_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeboundary',
            index=models.Index(fields=['parent'], name='core_admini_parent__a5a52d_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeboundary',
            index=models.Index(fields=['name'], name='core_admini_name_d1c9e3_idx'),
        ),
    ]
