# Generated by Django 4.2.25 on 2025-11-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(choices=[('sentinel1', 'Sentinel-1 (SAR Flood Detection)'), ('sentinel2', 'Sentinel-2 (Optical Validation)'), ('modis', 'MODIS (Global Monitoring)'), ('chirps', 'CHIRPS (Rainfall)'), ('gpm', 'NASA GPM (Precipitation)')], max_length=20)),
                ('data_type', models.CharField(choices=[('flood_extent', 'Flood Extent Mapping'), ('precipitation', 'Precipitation Data'), ('soil_moisture', 'Soil Moisture'), ('vegetation', 'Vegetation Index'), ('cloud_cover', 'Cloud Cover')], max_length=20)),
                ('location', models.CharField(help_text='Area covered by the data', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to satellite image tile')),
                ('geojson_data', models.JSONField(blank=True, help_text='GeoJSON flood polygons or features', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional satellite metadata')),
                ('capture_date', models.DateTimeField(help_text='When the satellite data was captured')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this data expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('cloud_cover', models.DecimalField(blank=True, decimal_places=2, help_text='Cloud cover percentage', max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-capture_date'],
                'indexes': [models.Index(fields=['satellite', 'data_type'], name='dashboard_s_satelli_c0ff8b_idx'), models.Index(fields=['location', 'capture_date'], name='dashboard_s_locatio_9e49a2_idx'), models.Index(fields=['is_active', 'expires_at'], name='dashboard_s_is_acti_33d612_idx')],
            },
        ),
    ]
