# Generated by Django 5.2.8 on 2026-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('parameter', models.CharField(default='river_level', max_length=50)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField(default=0.0)),
                ('severity', models.CharField(default='LOW', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
