name: Deploy FloodGuard to Contabo VPS

on:
  push:
    branches:
      - main  # Triggers automation whenever you push code changes to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Layers
        uses: actions/checkout@v4

      - name: SSH into Contabo Server and Execute Pull & Build Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 169.58.166.217
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /app/floodguard
            git pull --rebase=false origin main
            docker compose up -d --build
            docker compose exec -T web python manage.py migrate
            docker compose exec -T web python manage.py collectstatic --noinput
